#!/bin/python

import sys
import subprocess
import shlex
import os

confpath = "/root/.sshmap.conf"
dataDict = {}

def basicChecks():
	if(len(sys.argv) > 1):
		option = sys.argv[1]
	else:
		option = raw_input()
		if not option:
			print("Please provide the destination for which you wish to execute ssh command")
			exit()

	f = open(confpath, "r")
	for x in f:
	  data = x.split('::')
	  dataDict[data[0]] = data[1].rstrip()

	if option == 'list-options':
		for k in sorted (dataDict):
			print(k)
		exit()
	return option

def getSSHCommand(option):
	sshCMD = None
	if dataDict.has_key(option):
		sshCMD = dataDict[option]
	else:
		print("No ssh command mapping for destination " + option)
		exit()

	command = "copyq copy '" + sshCMD + "'"
	print command
	cmd = subprocess.Popen(shlex.split(command), stdout = subprocess.PIPE, stderr=subprocess.PIPE)
	output, error = cmd.communicate()
	returncode = cmd.returncode
	if returncode != 0:
		print("Error executing command", error)

option = basicChecks()
getSSHCommand(option)