#!/usr/bin/python3

import sys
import subprocess
import shlex
import os
from os.path import expanduser

home = expanduser("~")
confpath = home + "/.sshmap.conf"
dataDict = {}

def basicChecks():
	if(len(sys.argv) > 1):
		option = sys.argv[1]
	else:
		option = raw_input()
		if not option:
			print("Please provide the destination for which you wish to execute ssh command")
			exit()

	f = open(confpath, "r")
	for x in f:
	  data = x.split('::')
	  dataDict[data[0]] = data[1].rstrip()

	if option == 'list-options':
		for k in sorted (dataDict):
			print(k)
		exit()
	return option

def getSSHCommand(option):
	sshCMD = None
	if option in dataDict:
		sshCMD = dataDict[option]
	else:
		print("No ssh command mapping for destination " + option)
		exit()

	print(sshCMD)

option = basicChecks()
getSSHCommand(option)
